#!/usr/bin/ruby -K

require "tempfile"
require "optparse"

LDAPBASE = "dc=math,dc=kyoto-u,dc=ac,dc=jp"
LDAPMANAGER = "cn=Manager,#{LDAPBASE}"
LDAPOPTIONS = "-W -D #{LDAPMANAGER}"

$config = {}

$opts = OptionParser.new
$opts.on('-c', '--command=COMMAND', "Sub command: add, remove") do |command|
	set_mode command
end
$opts.on('-g', '--group=GROUP_CN', "Group to modify") do |group|
	$config[:group] = group
end
$opts.on('-u', '--user=UID', "User to add or remove") do |user|
	$config[:user] = user
end
$opts.on('-s', '--shell SHELL', "Login shell to change") do |shell|
	$config[:shell] = shell
end
$opts.on('-h', '--help', "Show help message") do |group|
	$config[:help] = true
end 

def set_mode(command)
	case (command)
	when 'add', 'add_to_group'
		$config[:command] = :add_to_group
	when 'remove', 'remove_from_group'
		$config[:command] = :remove_from_group
	when 'chsh', 'change_shell'
		$config[:command] = :change_shell
	else
		puts "No such command #{command}"
	end
end

$opts.order!(ARGV)
if (!ARGV.empty?) then
	set_mode(ARGV.shift)
	$opts.order!(ARGV)
end

def modify_impl(type, user, group)
	Tempfile.open('oa') do |temp|
		ldif = <<EOLdif
dn: cn=#{group},ou=Group,#{LDAPBASE}
changetype: modify
#{type}: memberUid
memberUid: #{user}
EOLdif
		temp.puts ldif
		temp.flush
		cmd = "ldapmodify #{LDAPOPTIONS} -f #{temp.path}"
		puts "###### LDIF file --- ######"
		puts ldif
		puts "###### --- LDIF file ######"
		puts cmd
		system cmd
	end
end

def add_to_group(user, group)
	modify_impl('add', user, group)
end

def remove_from_group(user, group)
	modify_impl('delete', user, group)
end

def change_shell(user, group)
	modify_impl('replace', user, shell)
end

def show_help(command)
	if (command) then
		case (command)
		when :add_to_group
			puts <<EOHelp
Usage: OA_ldapmodify add -u UID -g GROUP_CN
The add command adds the user into the group.

EOHelp
		when :remove_from_group
			puts <<EOHelp
Usage: OA_ldapmodify remove -u UID -g GROUP_CN
The remove command removes the user from the group.

EOHelp
		when :change_shell
			puts <<EOHelp
Usage: OA_ldapmodify chsh -u UID -s SHELL
The chsh command changes the user's login shell to SHELL.

EOHelp
		end
	else
		puts <<EOHelp
The OA_ldapmodify script manages LDAP users and groups.
You can specify one of sub commands: add, remove.
For more details about these commands, see the help.

EOHelp
		puts $opts
	end
end

if ($config[:help]) then
	show_help $config[:command]
	exit
end

case ($config[:command])
when :add_to_group
	add_to_group($config[:user], $config[:group])
when :remove_from_group
	remove_from_group($config[:user], $config[:group])
when :change_shell
	change_shell($config[:user], $config[:shell])
else
	puts $opts
end

