# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1239591128);
user_pref("app.update.lastUpdateTime.background-update-timer", 1239591127);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1239591127);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1239591128);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1239591128);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.startup.homepage", "http://www.math.kyoto-u.ac.jp/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.8");
user_pref("browser.tabs.forceHide", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.enabledItems", "langpack-en-GB@xulrunner-1.9.ubuntu.com:1.9.0.3,langpack-ja@xulrunner-1.9.ubuntu.com:1.9.0.3,ubufox@ubuntu.com:0.6,langpack-en-GB@firefox-3.0.ubuntu.com:3.0.3,langpack-ja@firefox-3.0.ubuntu.com:3.0.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.8");
user_pref("extensions.lastAppVersion", "3.0.8");
user_pref("intl.charsetmenu.browser.cache", "ISO-2022-JP, UTF-8, Shift_JIS");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.autoconfig_url", "http://wpad.kuins.net/proxy.pac");
user_pref("network.proxy.type", 2);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1242183130);
